// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that generates insights about esports matches using match data, player stats, and team performance.
 *
 * - generateEsportsInsights - A function that generates esports insights.
 * - GenerateEsportsInsightsInput - The input type for the generateEsportsInsights function.
 * - GenerateEsportsInsightsOutput - The return type for the generateEsportsInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEsportsInsightsInputSchema = z.object({
  matchData: z
    .string()
    .describe('Historical match data, player stats, and team performance.'),
});
export type GenerateEsportsInsightsInput = z.infer<
  typeof GenerateEsportsInsightsInputSchema
>;

const GenerateEsportsInsightsOutputSchema = z.object({
  insights: z
    .string()
    .describe('Key insights generated from the match data analysis.'),
});
export type GenerateEsportsInsightsOutput = z.infer<
  typeof GenerateEsportsInsightsOutputSchema
>;

export async function generateEsportsInsights(
  input: GenerateEsportsInsightsInput
): Promise<GenerateEsportsInsightsOutput> {
  return generateEsportsInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateEsportsInsightsPrompt',
  input: {schema: GenerateEsportsInsightsInputSchema},
  output: {schema: GenerateEsportsInsightsOutputSchema},
  prompt: `You are an expert esports analyst. Analyze the following Counter-Strike match data, player stats, and team performance data and provide key insights into competitive gaming.

Match Data:
{{matchData}}`,
});

const generateEsportsInsightsFlow = ai.defineFlow(
  {
    name: 'generateEsportsInsightsFlow',
    inputSchema: GenerateEsportsInsightsInputSchema,
    outputSchema: GenerateEsportsInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
